title: Beer Reviews
description: A data-driven story told by Group 15
show_downloads: false
google_analytics:
#theme: bubbling-ale
remote_theme: FoamFactory/bubbling-ale
url: https://s240440.github.io/
baseurl: # the subpath of your site, e.g. /blog/. Leave blank for root