title: Beer Reviews -  A data-driven story told by Group 15
description: Finale Project - Social Data Analysis and Visualization (02806)
google_analytics:
#theme: bubbling-ale
remote_theme: FoamFactory/bubbling-ale
url: https://s240440.github.io/
baseurl: # the subpath of your site, e.g. /blog/. Leave blank for root