title: Bubbling Ale theme
description: A data-driven story
show_downloads: true
google_analytics:
#theme: bubbling-ale
remote_theme: FoamFactory/bubbling-ale
url: https://s240440.github.io/
baseurl: # the subpath of your site, e.g. /blog/. Leave blank for root